vump db dump

diff --git a/vump b/vump
--- a/vump
+++ b/vump
@@ -545,16 +545,9 @@ function cmd_dbsave()
 
     # Dump Database to /tmp
     if ! docker exec $CONTAINER \
-        mysqldump -u$DB_USERNAME -p$DB_PASSWORD --single-transaction $DB_DATABASE > /tmp/backup.sql > /dev/null 2>&1;
+        mysqldump -u$DB_USERNAME -p$DB_PASSWORD --single-transaction $DB_DATABASE > backup.sql
     then
         echo "Error: Failed to dump database to /tmp/backup.sql"
-        exit 1
-    fi
-
-    # Copy backup file out of container
-    if ! docker cp $CONTAINER:/tmp/backup.sql ./backup.sql;
-    then
-        echo "Error: Unable to copy $CONTAINER:/tmp/backup.sql to current folder."
         exit 1
     fi
 
@@ -613,7 +606,7 @@ function cmd_dbfile()
     fi
 
     # Check docker container exists
-    if ! docker ps -a | grep "$CONTAINER" > /dev/null 2>&1; 
+    if ! docker ps -a --filter="name=${CONTAINER}" > /dev/null 2>&1; 
     then
         printf "\nError: Container $CONTAINER does not exist\n"
         exit 1
@@ -629,16 +622,9 @@ function cmd_dbfile()
 
     # Dump Database to /tmp
     if ! docker exec $CONTAINER \
-        mysqldump -u$DB_USERNAME -p$DB_PASSWORD --single-transaction $DB_DATABASE > /tmp/backup.sql > /dev/null 2>&1;
+        mysqldump -u$DB_USERNAME -p$DB_PASSWORD --single-transaction $DB_DATABASE > backup.sql;
     then
-        printf "\nError: Failed to dump database to /tmp/backup.sql\n"
-        exit 1
-    fi
-
-    # Copy backup file out of container
-    if ! docker cp $CONTAINER:/tmp/backup.sql ${FILENAME};
-    then
-        printf "\nError: Unable to copy $CONTAINER:/tmp/backup.sql to current folder.\n"
+        printf "\nError: Failed to dump database to ./backup.sql\n"
         exit 1
     fi
 
