vump_site db collation fix

diff --git a/inc/registry_functions b/inc/registry_functions
--- a/inc/registry_functions
+++ b/inc/registry_functions
@@ -12,14 +12,14 @@
 function push_to_registry()
 {
     clear
-    IMAGE_NAME="$IMAGE_NAME"
-    IMAGE_ID=$(docker image ls -q --filter reference=${IMAGE_NAME})
+    VUMP_IMAGE_NAME="$VUMP_IMAGE_NAME"
+    IMAGE_ID=$(docker image ls -q --filter reference=${VUMP_IMAGE_NAME})
 
     printf "${TEXT_RED_500} (you must be logged in with 'docker login' or 'az login acr')${RESET_TEXT}\n\n"
 
-    printf "The image $IMAGE_NAME:latest will be pushed to the following locations:\n"
-    printf "${ICON_CIRCLE} ${TEXT_GREEN_500}$REGISTRY_REPO:latest ${RESET_TEXT} \n"
-    printf "${ICON_CIRCLE} ${TEXT_GREEN_500}$REGISTRY_REPO:$IMAGE_ID ${RESET_TEXT} \n\n"
+    printf "The image $VUMP_IMAGE_NAME:latest will be pushed to the following locations:\n"
+    printf "${ICON_CIRCLE} ${TEXT_GREEN_500}$VUMP_REGISTRY_REPO:latest ${RESET_TEXT} \n"
+    printf "${ICON_CIRCLE} ${TEXT_GREEN_500}$VUMP_REGISTRY_REPO:$IMAGE_ID ${RESET_TEXT} \n\n"
     confirmation "Do you want to push image to container registry?"
 
     printf "\n"
@@ -28,8 +28,8 @@ function push_to_registry()
     # │                    PUSH WITH :HASH_ID                    │
     # ╰──────────────────────────────────────────────────────────╯
     # Tag :IMAGE_ID
-    echo "tag  ${IMAGE_NAME}:latest ${REGISTRY_REPO}:${IMAGE_ID}"
-    if ! docker image tag ${IMAGE_NAME}:latest ${REGISTRY_REPO}:${IMAGE_ID};
+    echo "tag  ${VUMP_IMAGE_NAME}:latest ${VUMP_REGISTRY_REPO}:${IMAGE_ID}"
+    if ! docker image tag ${VUMP_IMAGE_NAME}:latest ${VUMP_REGISTRY_REPO}:${IMAGE_ID};
     then
         printf "\n${TEXT_RED_500}Error: Failed to tag image with image ID.\n"
         exit 1
@@ -40,9 +40,9 @@ function push_to_registry()
     spin "docker_push_to_registry" "pushing :${IMAGE_ID} to registry" "push to registry"
 
     # Delete from local images
-    if ! docker image rm ${REGISTRY_REPO}:${IMAGE_ID};
+    if ! docker image rm ${VUMP_REGISTRY_REPO}:${IMAGE_ID};
     then
-        printf "\n${TEXT_RED_500}Error: Failed to remove ${REGISTRY_REPO}:${IMAGE_ID}.\n"
+        printf "\n${TEXT_RED_500}Error: Failed to remove ${VUMP_REGISTRY_REPO}:${IMAGE_ID}.\n"
         exit 1
     fi
 
@@ -52,9 +52,9 @@ function push_to_registry()
     # ╰──────────────────────────────────────────────────────────╯
 
     # Tag :Latest
-    if ! docker image tag ${IMAGE_NAME}:latest ${REGISTRY_REPO}:latest;
+    if ! docker image tag ${VUMP_IMAGE_NAME}:latest ${VUMP_REGISTRY_REPO}:latest;
     then
-        printf "\n${TEXT_RED_500}Error: Failed to tag image ${IMAGE_NAME}:latest as ${REGISTRY_REPO}:latest.\n"
+        printf "\n${TEXT_RED_500}Error: Failed to tag image ${VUMP_IMAGE_NAME}:latest as ${VUMP_REGISTRY_REPO}:latest.\n"
         exit 1
     fi
 
@@ -63,9 +63,9 @@ function push_to_registry()
     spin "docker_push_to_registry" "pushing :latest to registry" "push to registry"
 
     # Delete from local images
-    if ! docker image rm ${REGISTRY_REPO}:latest;
+    if ! docker image rm ${VUMP_REGISTRY_REPO}:latest;
     then
-        printf "\n${TEXT_RED_500}Error: Failed to remove ${REGISTRY_REPO}:latest.\n"
+        printf "\n${TEXT_RED_500}Error: Failed to remove ${VUMP_REGISTRY_REPO}:latest.\n"
         exit 1
     fi
 
@@ -75,7 +75,7 @@ function push_to_registry()
 # Push to the registry.
 function docker_push_to_registry()
 {
-    if ! docker push ${REGISTRY_REPO}:${PUSH_TAG};
+    if ! docker push ${VUMP_REGISTRY_REPO}:${PUSH_TAG};
     then
         printf "\n${TEXT_RED_500}Error: Failed to push ${PUSH_REGISTRY}:${PUSH_TAG} to container registry.\n"
         exit 1
@@ -100,9 +100,9 @@ function pull_from_registry()
 # Pull from registry
 function docker_pull_from_registry()
 {
-    if ! docker pull ${REGISTRY_REPO}:${PULL_TAG};
+    if ! docker pull ${VUMP_REGISTRY_REPO}:${VUMP_PULL_TAG};
     then
-        printf "\n${TEXT_RED_500}Error: Failed to pull ${PUSH_REGISTRY}:${PULL_TAG} from container registry.\n"
+        printf "\n${TEXT_RED_500}Error: Failed to pull ${PUSH_REGISTRY}:${VUMP_PULL_TAG} from container registry.\n"
         exit 1
     fi
 }
